# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MCmqs <- function(N, n, beta) {
    .Call(`_mqs_MCmqs`, N, n, beta)
}

mqse <- function(Y, beta = 0.5, q = NULL, alpha = 0.05, conf = FALSE, type = "runs") {
    .Call(`_mqs_mqse`, Y, beta, q, alpha, conf, type)
}

