// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// MCsimulation
NumericVector MCsimulation(int N, int n, double beta);
RcppExport SEXP _mqs_MCsimulation(SEXP NSEXP, SEXP nSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(MCsimulation(N, n, beta));
    return rcpp_result_gen;
END_RCPP
}
// MQSE
List MQSE(NumericVector Y, double beta, Rcpp::Nullable<double> q, double alpha, bool conf, std::string type);
RcppExport SEXP _mqs_MQSE(SEXP YSEXP, SEXP betaSEXP, SEXP qSEXP, SEXP alphaSEXP, SEXP confSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type conf(confSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(MQSE(Y, beta, q, alpha, conf, type));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mqs_MCsimulation", (DL_FUNC) &_mqs_MCsimulation, 3},
    {"_mqs_MQSE", (DL_FUNC) &_mqs_MQSE, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_mqs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
