# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MCsimulation <- function(N, n, beta) {
    .Call(`_mqs_MCsimulation`, N, n, beta)
}

mqs <- function(Y, beta = 0.5, q = NULL, alpha = 0.05, type = "runs") {
    .Call(`_mqs_mqs`, Y, beta, q, alpha, type)
}

